name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  GOPRIVATE: github.com/infracost/*
  TARGET_ORG: infracost

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: infracost/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.INFRACOST_CI_APP_ID }}
          private-key: ${{ secrets.INFRACOST_CI_APP_PRIVATE_KEY }}
          owner: ${{ env.TARGET_ORG }}
          repositories: cli,config

      - run: |
          git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/".insteadOf "https://github.com/"

      - name: Configure private Go modules
        run: git config --global url."https://${{ secrets.GO_PRIVATE_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - run: go test ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: infracost/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.INFRACOST_CI_APP_ID }}
          private-key: ${{ secrets.INFRACOST_CI_APP_PRIVATE_KEY }}
          owner: ${{ env.TARGET_ORG }}
          repositories: cli,config

      - run: |
          git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/".insteadOf "https://github.com/"

      - name: Configure private Go modules
        run: git config --global url."https://${{ secrets.GO_PRIVATE_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - uses: golangci/golangci-lint-action@v7
        with:
          version: v2.4

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: infracost/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.INFRACOST_CI_APP_ID }}
          private-key: ${{ secrets.INFRACOST_CI_APP_PRIVATE_KEY }}
          owner: ${{ env.TARGET_ORG }}
          repositories: cli,config

      - run: |
          git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/".insteadOf "https://github.com/"

      - name: Check formatting
        run: test -z "$(gofmt -l .)"
